name: Publish to Public Repo
on:
  push:
    tags:
      - 'v*'   # 只要你 push 形如 v1.2.3 的 tag，就会触发

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 根据 .gitattributes 生成“干净导出”
      - name: Make clean export
        run: |
          mkdir -p /tmp/out
          git archive --format=tar HEAD | tar -x -C /tmp/out
          echo "Exported tree:"
          ls -la /tmp/out

      # 强推到公开仓库 Prism 的 main（并同步 tag）
      - name: Push to public repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLIC_REPO: ${{ secrets.PUBLIC_REPO }}
        run: |
          cd /tmp/out
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: publish ${GITHUB_REF##*/}"
          git branch -M main
          git remote add origin "https://x-access-token:${GH_TOKEN}@${PUBLIC_REPO#https://}"
          git push -f origin main
          git tag "${GITHUB_REF##*/}"
          git push origin "${GITHUB_REF##*/}"
